import Head from 'next/head'
import Image from 'next/image'

import { useEffect, useRef, useState } from 'react'

import gsap from 'gsap'

export default function Home() {
  const test1 = useRef<HTMLDivElement>(null)
  const test2 = useRef<HTMLDivElement>(null)
  const test3 = useRef<HTMLDivElement>(null)
  const containerRef = useRef<HTMLDivElement>(null)

  const [background, setBackground] = useState('blue')

  const toggleBackground = () => {
    const color = background === 'blue' ? 'orange' : 'blue'
    setBackground(color)

    console.log('button is clicked')
  }

  useEffect(() => {
    gsap.to(containerRef.current, {
      duration: 1,
      backgroundColor: background,
      ease: 'none',
    })
    console.log('bg color is changed')
  }, [background])

  console.log('Global : ', test1)

  useEffect(() => {
    // console.log('in useEffect test 1 : ', test1)
    // console.log('test 2 : ', test2)
    //console.log('test 3 : ', test3)

    // gsap.from(containerRef.current, {
    //   duration: 1,
    //   delay: 1,
    //   backgroundColor: 'green',
    //   autoAlpha: 0,
    //   ease: 'none',
    // })

    gsap.to(test1.current, {
      delay: 1,
      duration: '2',
      ease: 'none',
      color: 'yellow',
    })
  })

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container" ref={containerRef}>
        <div id="text-test1" ref={test1}>
          this is test 1
        </div>
        <div id="text-test2" ref={test2}>
          this is test 2
        </div>
        <div id="text-test3" ref={test3}>
          this is test 3
        </div>

        <button onClick={() => toggleBackground()}>toggle background</button>
      </div>
    </div>
  )
}
