import Head from 'next/head'
import Image from 'next/image'

import gsap from 'gsap'
import { useEffect, useRef, useState } from 'react'

export default function Home() {
  const test1 = useRef<HTMLDivElement>(null)
  const test2 = useRef<HTMLDivElement>(null)
  const test3 = useRef<HTMLDivElement>(null)

  console.log('Global : ', test1)

  useEffect(() => {
    console.log('in useEffect test 1 : ', test1)
    console.log('test 2 : ', test2)
    console.log('test 3 : ', test3)
  }, [test1, test2, test3])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main
        className="main"
        ref={(el) => {
          logoItem = el
        }}>
        <div>test</div>
        <div
          ref={(el) => {
            textItem = el
          }}
          className="text_item1">
          Item1
        </div>
        <div
          className="text_item1"
          ref={(el) => {
            setTestItem
          }}>
          Test Item
        </div>
      </main> */}
      <main className="main">
        <div id="text-test1" ref={test1}>
          this is test 1
        </div>
        <div id="text-test2" ref={test2}>
          this is test 2
        </div>
        <div id="text-test3" ref={test3}>
          this is test 3
        </div>
      </main>
    </div>
  )
}
